### ISSUE TITLE
RuntimeError: softmax() Expected a value of type 'Optional[Tensor]' for argument 'ptr' but instead found type 'int'

### ISSUE THREAD

**Issue by lvjiujin** [ljin0429/CAD-Net#1]
`(gcn_test) root@hecs-x-large-2-linux-20210127093009:~/CAD-NET/CAD-Net/src# python demo_cora.py
/root/anaconda3/envs/gcn_test/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "demo_cora.py", line 140, in <module>
    train(model, optimizer, data)
  File "demo_cora.py", line 78, in train
    out, ent, _ = model(data, is_debug=False)
  File "/root/anaconda3/envs/gcn_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "demo_cora.py", line 67, in forward
    x, ent, debug_tensor = self.adgs(x, edge_index, train_mask, is_debug)
  File "/root/anaconda3/envs/gcn_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/CAD-NET/CAD-Net/src/AdaCAD_cora.py", line 30, in forward
    transP, sum_pipj = self.compute_transP(cd, edge_index)
  File "/root/CAD-NET/CAD-Net/src/AdaCAD_cora.py", line 78, in compute_transP
    transP = softmax(pipj, row, cd.size(0))
RuntimeError: softmax() Expected a value of type 'Optional[Tensor]' for argument 'ptr' but instead found type 'int'.
Position: 2
Value: 2708
Declaration: softmax(Tensor src, Tensor? index=None, Tensor? ptr=None, int? num_nodes=None, int dim=0) -> (Tensor)
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)`

**Comment by lvjiujin** [comment]
AdaCAD_cora.py line 78 should modified:
from 
`transP = softmax(pipj, row, cd.size(0))`
to 
`transP = softmax(pipj, row, num_nodes = cd.size(0))`
